name: dhpp

services:
  api:
    container_name: container-dhhp-api
    env_file:
      - .env
    restart: always
    ports: 
      - "8000:8000"
    build: 
      context: "./"
      dockerfile: Dockerfile-Api
    volumes:
      - ./:/dhpp-api
    networks:
      - api-compose-networks

  postgres:
    container_name: container-dhhp-postgres
    env_file:
     - .env
    restart: always
    ports: 
      - "5432:5432"
    build: 
      context: "./docker"
      dockerfile: Dockerfile-Postgres

    environment:
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
      POSTGRES_DB: ${DATABASE_POSTGRES}
    volumes:
      - ./docker/configs/pg_hba.conf:/var/postgres/data/pg_hba.conf
    networks:
      - api-compose-networks
      
networks:
  api-compose-networks:
    driver: bridge
