-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cartorio
(
    id serial NOT NULL,
    nome character varying(15) COLLATE pg_catalog."default",
    fk_delegado serial NOT NULL,
    CONSTRAINT cartorio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contato
(
    id serial NOT NULL,
    celular character varying(11) COLLATE pg_catalog."default",
    telefone character varying(11) COLLATE pg_catalog."default",
    email character varying(20) COLLATE pg_catalog."default",
    fk_pessoa serial NOT NULL,
    CONSTRAINT contato_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.delegado
(
    id serial NOT NULL,
    oab character varying(10) COLLATE pg_catalog."default",
    fk_pessoa serial NOT NULL,
    CONSTRAINT delegado_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.endereco
(
    id serial NOT NULL,
    logradouro character varying(100) COLLATE pg_catalog."default",
    n_residencia character varying COLLATE pg_catalog."default",
    bairro character varying(100) COLLATE pg_catalog."default",
    cidade character varying(100) COLLATE pg_catalog."default",
    cep character varying(8) COLLATE pg_catalog."default" NOT NULL,
    uf character varying(2) COLLATE pg_catalog."default",
    fk_pessoa serial NOT NULL,
    CONSTRAINT endereco_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.envolvidos_inquerito
(
)
;

CREATE TABLE IF NOT EXISTS public.escrivao
(
    id serial NOT NULL,
    fk_pessoa serial NOT NULL,
    fk_cartorio serial NOT NULL,
    CONSTRAINT escrivao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inquerito
(
    id serial NOT NULL,
    n_sinesp character varying COLLATE pg_catalog."default" NOT NULL,
    n_ip character varying COLLATE pg_catalog."default",
    tipo character varying COLLATE pg_catalog."default",
    data_instaraucao timestamp with time zone,
    data_ocorrencia timestamp with time zone,
    CONSTRAINT inquerito_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pessoa
(
    id serial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nome_social character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nascimento timestamp without time zone NOT NULL,
    cpf character varying(11) COLLATE pg_catalog."default" NOT NULL,
    sexo character varying(1) COLLATE pg_catalog."default" NOT NULL,
    etnia text COLLATE pg_catalog."default",
    identidade_genero text COLLATE pg_catalog."default",
    pdc text COLLATE pg_catalog."default",
    CONSTRAINT pessoa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.processo
(
    id serial NOT NULL,
    n_peocesso character varying COLLATE pg_catalog."default",
    representacao_judicial character varying COLLATE pg_catalog."default",
    cumprimento_mandado character varying COLLATE pg_catalog."default",
    fk_inquerito serial NOT NULL,
    CONSTRAINT processo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.suspeito
(
    id serial NOT NULL,
    faccao character varying(15) COLLATE pg_catalog."default",
    vulgo character varying(10) COLLATE pg_catalog."default",
    fk_pessoa serial NOT NULL,
    CONSTRAINT suspeito_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id serial NOT NULL,
    usuario character varying(20) COLLATE pg_catalog."default" NOT NULL,
    senha character varying COLLATE pg_catalog."default",
    fk_pessoa serial NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vitima
(
    id serial NOT NULL,
    faccao character varying(15) COLLATE pg_catalog."default",
    vulgo character varying(10) COLLATE pg_catalog."default",
    fk_pessoa serial NOT NULL,
    CONSTRAINT vitima_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cartorio
    ADD CONSTRAINT fk_delegado FOREIGN KEY (fk_delegado)
    REFERENCES public.delegado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contato
    ADD CONSTRAINT fk_pessoa FOREIGN KEY (id)
    REFERENCES public.pessoa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS contato_pkey
    ON public.contato(id);


ALTER TABLE IF EXISTS public.delegado
    ADD CONSTRAINT fk_pessoa FOREIGN KEY (fk_pessoa)
    REFERENCES public.pessoa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.endereco
    ADD CONSTRAINT fk_pessoa FOREIGN KEY (fk_pessoa)
    REFERENCES public.pessoa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.escrivao
    ADD CONSTRAINT fk_cartorio FOREIGN KEY (fk_cartorio)
    REFERENCES public.cartorio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.escrivao
    ADD CONSTRAINT fk_pessoa FOREIGN KEY (fk_pessoa)
    REFERENCES public.pessoa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.processo
    ADD CONSTRAINT fk_inquerito FOREIGN KEY (fk_inquerito)
    REFERENCES public.inquerito (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.suspeito
    ADD CONSTRAINT fk_pessoa FOREIGN KEY (fk_pessoa)
    REFERENCES public.pessoa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT fk_pessoa FOREIGN KEY (fk_pessoa)
    REFERENCES public.pessoa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vitima
    ADD CONSTRAINT fk_pessoa FOREIGN KEY (fk_pessoa)
    REFERENCES public.pessoa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;